#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5962-web
    bind *:80
    mode http
    balance roundrobin
    server 5962-web-01 3.89.244.51:80 check
    server 5962-web-02 107.23.186.148:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
