#!/usr/bin/env bash
# script installs HA proxy and configures it

sudo apt-get update
sudo apt-get install haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.real.cfg

echo "frontend http
  bind *:80
  mode http
  default_backend site_backend
  
  backend site_backend
  balance roundrobin
  server 5962-web-01 3.89.244.51:80 check
  server 5962-web-02 107.23.186.148:80 check
  " | sudo tee -a /etc/haproxy/haproxy.cfg
  
