#!/usr/bin/env bash
#Installing Nginx on Ubuntu
#Nginx is listening on port 80
#The GET request should return a page containing "Holberton School"

sudo apt-get update && upgrade
sudo apt-get install nginx -y

#Display your message then
sudo echo "Holberton School" > /var/www/webpage/index.html
printf %s "server{
  listen 80 default_server;
  listen [::]:80 default server;
  root /var/www/webpage;
  index index.html}" >> /etc/nginx/available-sites/default
sudo service nginx restart
