#!/usr/bin/env bash
# installs nginx and configures it

apt-get update
apt-get -y install nginx

echo "<html><body>Holberton School</body></html>" > /var/www/mywebsite.com/html/index.html

printf %s "server{
       listen 80;
       listen [::]:80;
       root /var/www/mywebsite.com/html/
       index index.html;
       location {
       try_files $uri $uri/ =404;
       }

       }" > /etc/nginx/sites-available/default

nginx -s reload
