#!/usr/bin/env bash
# Installs Nginx on a server

sudo apt -y update
sudo apt install -y nginx
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;

}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
