#!/usr/bin/env bash
#script redirects to the google page

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-enabled/default #add at line 30

sudo service nginx restart
